module.exports.help = require('./help/index.js')
module.exports.exists = require('./exists/index.js')
module.exports.format = require('./format/index.js')
module.exports.notify = require('./notify/index.js')
module.exports.settings = require('./settings/index.js')
