module.exports.clear = require('./contents/clear.js')
module.exports.activated = require('./contents/activated.js')
module.exports.comingSoon = require('./contents/comingSoon.js')
module.exports.deactivated = require('./contents/deactivated.js')
module.exports.settingsFile = require('./contents/settingsFile.js')
module.exports.noSettingsFile = require('./contents/noSettingsFile.js')
